# -*- coding: utf-8 -*-
import json, re, collections

AXES = {
"İbadet ve Kulluk": ["namaz","cami","hac","umre","abdest","zikir","dua","kulluk","ezan","cemaat","cuma namazı","cuma günü","itikaf","teravih","tavaf","arafat","ibadet bilinci","ibadetin özü","dinin direği","beş vakit namaz","cemaatle namaz","cemaatle ibadet","hutbe adabı","hutbe dinleme adabı","cami adabı","huşu","sahur","ibadet","camiler","cami inşası","cami yardımı","camiler haftası","din görevlileri haftası","camiler ve din görevlileri haftası"],

"Ramazan, Oruç ve Bayramlar": ["ramazan","oruç","ramazan bayramı","kurban bayramı","bayram sevinci","bayram tebriği","bayramlaşma","üç aylar","ramazan ayı","ramazana veda","zilhicce","kurban","kurban ibadeti","kurban kesimi","kurban kesim adabı","vekaletle kurban","vekaleten kurban","teşrik tekbirleri","fıtır sadakası","hac ön kayıt","mübarek üç aylar","kurban bayramı hazırlığı","bayram namazı","bayram"],

"Kandiller, Muharrem ve Mübarek Geceler": ["kadir gecesi","berat gecesi","berat kandili","miraç kandili","miraç gecesi","mevlid kandili","mevlid-i nebi","isra ve miraç","miraç","regaib gecesi","muharrem ayı","muharrem","kerbela","kerbelâ","hz. hüseyin","aşure","aşure günü","hicri yılbaşı","hicri yıl","yılbaşı","yeni yıl","kandil","bin aydan hayırlı gece","kutlu doğum haftası","şaban ayı","recep ayı","receb ayı","af ve mağfiret"],

"İman, Tevhid ve Ahiret": ["iman","iman esasları","tevhid","tevhid inancı","tevhid ve vahdet","ahiret","ahiret bilinci","ahirete iman","hesap günü","hesap verme bilinci","mağfiret","tövbe","istiğfar","arınma","manevi arınma","ihlas","ihlas suresi","hidayet","gaflet","teslimiyet","kelime-i şehadet","şirk","mahşer","kıyamet","mizan","ölüm","ölüme hazırlık","peygamberlere iman","iman-amel bütünlüğü","kulluk misakı","islam'ın şartları","islam'ın kaynakları","kalb-i selim","gayb bilgisi","cennet","cennet müjdesi","amel defteri","kulluk şuuru","esma-i hüsna","allah'ın isimleri","allah’ın isimleri","dünya hayatının geçiciliği","şükür"],

"Kur'an-ı Kerim": ["kur'an","kur’an","kur'an-ı kerim","kur'an ayı","kur'an ile buluşma","kuran ve sünnet","kur'an ve sünnet","yaz kur'an kursları","yaz kur'an kursu","kur'an kursu","kur'an kursu öğreticileri","vahiy","ilk vahiy","asr suresi","inşirah suresi","mucize","en büyük mucize"],

"Peygamberimiz ve Ashab": ["peygamber sevgisi","hz. muhammed","veda hutbesi","ensar ve muhacir","sünnet","sünnete bağlılık","hicret","hz. hatice","hz. ömer","hz. ebu bekir","hz. âişe","hz. i̇brahim","hz. ibrahim","hz. eyyûb","hz. âdem","hz. adem","hz. âdem ve havva","habil ve kabil","ashâb-ı kehf","selman-ı farisi","bilal-i habeşi","muaz b. cebel","cibril hadisi","örnek şahsiyet","peygamber örnekliği","peygamberimiz ve aile","peygamberimizin ahlakı","peygambere iman","nübüvvet","rahmet peygamberi","muhammedü'l-emin","tebliğ","sahabi kıssası","genç sahabiler","mekke'nin fethi","medine","salavat","ehl-i beyt","peygamberimiz ve vefa toplumu","ahde vefa","mevlid-i nebi"],

"Ahlak, Erdem ve Söz": ["güzel ahlak","ahlak","ahlak eğitimi","dürüstlük","doğruluk","samimiyet","vicdan","hayâ","iffet","gıybet","din istismarı","dinin istismarı","iyilik","edep","edeb","kibir","haset","dargınlık","kötü söz","yalan","yalan haber","dedikodu","fitne","iftira","riya","tevazu","affetmek","af ve bağışlama","affedicilik","güzel söz","örnek ahlak","ahlaki yozlaşma","değerlere yabancılaşma","tembellik","kusur örtmek","esenlik dilemek","tebessüm","kırgınlıkları gidermek","toplumsal ahlak","kardeşlik ahlakı","güzel isim"],

"Aile, Çocuk ve Nesil": ["aile","evlilik","çocuk eğitimi","anne baba hakkı","anne baba sorumluluğu","anne baba rolü","ebeveyn sorumluluğu","ebeveynlik","nikah","nikâh","boşanma","aile huzuru","aile bağları","aile kurumu","aile mahremiyeti","aile hukuku","aile içi iletişim","aile ahlakı","aile çözülmesi","aile içi şiddet","kadına yönelik şiddet","kadına şiddet","düğün adabı","düğün israfı","evlilik teşviki","eşler arası sevgi","eşler arası ilişki","çocuk hakları","çocuk terbiyesi","çocuk sevgisi","çocuk istismarı","sokak çocukları","yetim","yetimler","yetimlere sahip çıkmak","akran zorbalığı","nesil yetiştirme","gençlik","kürtaj","yaşlılara saygı","vefa","eş ve anne olarak kadın","kadın hakları","kadın örnek şahsiyetler"],

"Toplumsal Dayanışma, Merhamet ve Kardeşlik": ["kardeşlik","kardeşlik hukuku","müslüman kardeşliği","kardeşlik bağları","kardeşlik ve birlik","birlik ve kardeşlik","dayanışma","yardımlaşma","paylaşma","merhamet","şefkat","hoşgörü","birlik ve beraberlik","birlik beraberlik","birlik ruhu","birlik ve dirlik","milli birlik","eşitlik","ayrımcılık","ayrımcılık karşıtlığı","insan onuru","insanlık ailesi","sıla-i rahim","akraba ziyareti","adalet","kul hakkı","kamu hakkı","toplumsal güven","toplumsal sorumluluk","toplumsal duyarlılık","toplumsal saygı","toplumsal onur","komşuluk","hasta ziyareti","taziye","cenaze adabı","organ bağışı","empati","diğerkâmlık","güven","güvenilirlik","saygı","mazlumun yanında olmak","zulme karşı durmak","zulme rıza","ümmet","ümmet bilinci","ümmet birliği","mezhep birliği","mezhepçilik","vahdet","tefrika","ırkçılık karşıtlığı","engellilik","engellilik farkındalığı","engelliler haftası","engellilere değer vermek","erişilebilirlik","toplumsal huzur","sosyal ilişkiler"],

"Ekonomik Hayat: Kazanç, Zekat ve İsraf": ["helal kazanç","haksız kazanç","haram kazanç","helal ticaret","helal lokma","helal haram","ticaret ahlakı","iş ahlakı","çalışma ahlakı","işçi hakları","işçi işveren ilişkisi","iş güvenliği","zekât","zekat","zekat ve fitre","sadaka","sadaka-i câriye","infak","kalıcı hayır","hayır kurumları","vakıf","yardım kampanyası","karaborsacılık","faiz","kumar","şans oyunları","kumar ve şans oyunları","alkol ve kumar","israf","ekmek israfı","tüketim kültürü","tüketim ahlakı","tüketim çılgınlığı","ölçü tartı","alın teri","ahilik","emek","çalışma bilinci","liyakat","şüpheli şeyler","türkiye diyanet vakfı"],

"Vatan, Millet ve Tarih": ["vatan","vatan sevgisi","vatan savunması","şehit","şehitlik","mehmetçik","çanakkale","çanakkale zaferi","malazgirt","malazgirt zaferi","istanbul'un fethi","kurtuluş savaşı","milli mücadele","milli mücadele ruhu","istiklal mücadelesi","istiklal marşı","bağımsızlık","15 temmuz","15 temmuz darbe girişimi","darbe girişimi","fetö","feto","30 ağustos","30 ağustos zaferi","zafer","büyük taarruz","tarih bilinci","milli ve manevi değerler","kimlik","kimlik inşası","şahsiyet inşası","millet ruhu","güvenlik güçleri","terör","terör saldırısı","terör saldırıları","ankara terör saldırısı","ankara saldırısı","can dokunulmazlığı","can güvenliği","cana kıymanın haramlığı","asker duası"],

"İslam Coğrafyası ve Küresel Meseleler": ["gazze","gazze soykırımı","gazze direnişi","filistin","kudüs","mescid-i aksa","mülteciler","suriye insani yardım","doğu türkistan","azerbaycan","arnavutluk","zulüm","mazlumun bedduası","mazlumlara destek","soykırım","işgal","boykot"],

"Sabır, Tevekkül ve Manevi Olgunluk": ["sabır","tevekkül","imtihan","nankörlük","muhasebe","nefis muhasebesi","nefis terbiyesi","yıl sonu muhasebesi","öz muhasebe","zaman muhasebesi","sorumluluk bilinci","sorumluluk","istikamet","takva","salih amel","tedbir","itidal","denge","dünya-ahiret dengesi","dünya ahiret dengesi","kanaat","huzur","kalp huzuru","gönül terbiyesi","murakabe","manevi yükseliş","manevi gelişim","manevi iklim","fıtrat","dosdoğru olmak","sırat-ı müstakim","ihsan","hakikat","zaman bilinci","zaman yönetimi","zamanı değerlendirmek","zamanın kıymeti","nimetlerin kıymeti","nimet","rızık","öfke kontrolü","yalnızlık","yalnızlaşma","bireyselleşme","bireysellik"],

"Afet, Kriz ve Sağlık": ["deprem","van depremi","afet","afetler","afet bilinci","maden kazası","ermenek maden kazası","orman yangınları","salgın","salgın hastalık","salgın tedbirleri","salgından kurtuluş","sağlık","şifa","hijyen","trafik güvenliği","madde bağımlılığı","uyuşturucu","alkol","bağımlılık","açlık","kuraklık","yağmur duası","başsağlığı"],

"Eğitim, Teknoloji, Çevre ve Toplumsal Değişim": ["ilim","eğitim","din eğitimi","dini eğitim","sahih dini bilgi","dini bilgi","öğretmenler günü","öğretmenlik","seçmeli dersler","eğitim öğretim yılı","değerler eğitimi","üniversite sınavı","dijital bağımlılık","teknoloji bağımlılığı","sosyal medya","sosyal medya ahlakı","dijital tehlikeler","mahremiyet","mahremiyet ihlali","çevre","çevre kirliliği","çevre bilinci","doğal denge","hayvan hakları","kültür erozyonu","dünyevileşme","hurafe","cehalet","sahih din anlayışı"],
}

print("axis count:", len(AXES))
for a,terms in AXES.items():
    print(f"{a}: {len(terms)} terim")

json.dump(AXES, open("/sessions/happy-trusting-turing/mnt/outputs/hutbe_work/axes.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
